FROM jupyter/scipy-notebook:de0cd8011b9e

#
# Create the standard directory structure
# for nbgrader
#
USER root
RUN mkdir -p /exchange/course/outbound
RUN mkdir -p /exchange/course/inbound
RUN chown -R jovyan /exchange
RUN chmod a+rwx /exchange

USER jovyan
RUN conda install --yes -c conda-forge nbgrader
WORKDIR /home/jovyan
